# Welcome to Jekyll!
#

# Site settings
title: Spirit Fire
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Team Spirit Fire # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: dustin@dustinpeerce.com
baseurl: "/Spirit-Fire-Page" # the subpath of your site, e.g. /blog
url: "http://dustinpeerce.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/DustinPeerce
  github: https://github.com/dustinpeerce
  linkedin-square: https://linkedin.com/in/dustinpeerce
  facebook-official: https://facebook.com/dustin.peerce
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
